In [6]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable


In [7]:
!pip install seaborn

Defaulting to user installation because normal site-packages is not writeable


In [8]:
!pip install matplotlib

Defaulting to user installation because normal site-packages is not writeable


In [3]:
import numpy as np

In [4]:
array = np.arange(1,10,2)

In [5]:
array

array([1, 3, 5, 7, 9])

In [6]:
array1 = np.arange(11,20,2)

In [7]:
array1

array([11, 13, 15, 17, 19])

In [8]:
array2 = np.arange(21,30,2)

In [9]:
array2

array([21, 23, 25, 27, 29])

In [10]:
array3 = np.array([[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]])

In [11]:
array3.ndim

3

In [12]:
array3

array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]])